# Generated by Django 2.2.10 on 2021-09-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
