# Generated by Django 2.2.10 on 2021-09-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0002_remove_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='callapp.profile'),
        ),
    ]
