# Generated by Django 2.2.10 on 2021-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0004_auto_20210921_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.TextField(default='pending', null=True, verbose_name='Status'),
        ),
    ]
