# Generated by Django 2.2.10 on 2021-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0005_auto_20210923_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cc_myself',
        ),
        migrations.AddField(
            model_name='book',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=250),
        ),
    ]
